#!/bin/bash

sudo initctl stop newrelic-infra

INSTANCE_IP=$(curl --silent 169.254.169.254/latest/meta-data/local-ipv4)
INSTANCE_NAME="instance_tag_name"

# Template file newrelic-infra.pad
sudo cp /home/ec2-user/newrelic-infra.pad /etc/newrelic-infra.yml

sed -i 's/__INSTANCE_NAME__/'${INSTANCE_NAME}'/' /etc/newrelic-infra.yml

sed -i 's/__INSTANCE_IP__/'${INSTANCE_IP}'/' /etc/newrelic-infra.yml

sudo initctl start newrelic-infra
